// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTOvLnDa7rJ24zAhNojywe76qE7T4E5M',
    appId: '1:134573180968:android:a87e52287b0fc9309f8d1d',
    messagingSenderId: '134573180968',
    projectId: 'pulse-rifle-app',
    storageBucket: 'pulse-rifle-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKziHwRYp0KVCQ5Siwh72tuur6UgIfX5E',
    appId: '1:134573180968:ios:5728acceedf1f1be9f8d1d',
    messagingSenderId: '134573180968',
    projectId: 'pulse-rifle-app',
    storageBucket: 'pulse-rifle-app.firebasestorage.app',
    iosBundleId: 'com.example.rtTiltcantAccgyro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKziHwRYp0KVCQ5Siwh72tuur6UgIfX5E',
    appId: '1:134573180968:ios:5728acceedf1f1be9f8d1d',
    messagingSenderId: '134573180968',
    projectId: 'pulse-rifle-app',
    storageBucket: 'pulse-rifle-app.firebasestorage.app',
    iosBundleId: 'com.example.rtTiltcantAccgyro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqDt3j7j5uPVSfuPtJgomCaNqhOrqoU04',
    appId: '1:134573180968:web:58f1ec4e46e57bdd9f8d1d',
    messagingSenderId: '134573180968',
    projectId: 'pulse-rifle-app',
    authDomain: 'pulse-rifle-app.firebaseapp.com',
    storageBucket: 'pulse-rifle-app.firebasestorage.app',
    measurementId: 'G-B93X4XGBWZ',
  );
}
